### ISSUE TITLE
Pagination fails over ldaps

### ISSUE THREAD

**Issue by Denney-tech** [jborean93/PSOpenAD#19] opened 2022-06-10 20:38 UTC
Hello again! New enterprise environment, single domain, ~37% more targets. Appears to fail after the 3rd page. If I use ldap, there's no issue and returns all ~22k results. Issue is the same if the global catalog is used. TLS Certificates appear to be using stronger cryptography as I'm not getting any trust issues when testing openssl connections with internal domain services.

Running on WSL2 > Distrod > Fedora 36 container. /etc/krb5.conf is configured and kinit was run to enable implicit kerberos authentication without needing to join the linux container to domain.

Using PowerShell 7.2.4 and PSOpenAD 0.1.0.preview3

``` powershell
$computers = Get-OpenADComputer -Server ldaps://dc01.contoso.com:636 -Verbose -Debug
VERBOSE: Connecting to ldaps://dc01.hobbylobby.corp:636/
VERBOSE: Performing TLS handshake on connection
VERBOSE: Default authentiation mechanism has been set to Negotiate
VERBOSE: SASL auth complete - Will Sign False - Will Encrypt False
VERBOSE: Starting LDAP search request at '' for Base - (objectClass=*)
VERBOSE: Starting LDAP search request at 'CN=Aggregate,CN=Schema,CN=Configuration,DC=contoso,DC=com' for Base - (objectClass=*)
VERBOSE: Starting LDAP search request at 'DC=contoso,DC=com' for Subtree - (objectCategory=computer)
VERBOSE: Receive pagination result, sending new search request
VERBOSE: Receive pagination result, sending new search request
VERBOSE: Receive pagination result, sending new search request
Get-OpenADComputer: The encoded length exceeds the number of bytes remaining in the input buffer.

PS /> $Error.FullyQualifiedErrorId
System.Formats.ASn1.AsnContentException,PSOpenAD.Commands.GetOpenADComputer

PS /> $Error.Exception

TargetSite     : PSOpenAD.LDAP.LDAPMessage WaitForMessage(Int32, System.Nullable`1[System.Int32], System.Threading.CancellationToken)
Message        : The encoded length exceeds the number of bytes remaining in the input buffer.
Data           : {}
InnerException : 
HelpLink       : 
Source         : PSOpenAD
HResult        : -2146233088
StackTrace     :    at PSOpenAD.OpenADConnection.WaitForMessage(Int32 messageId, Nullable`1 timeout, CancellationToken cancelToken) in /home/runner/work/PSOpenAD/PSOpenAD/src/Connection.cs:line 78
                    at PSOpenAD.Operations.LdapSearchRequest(OpenADConnection connection, String searchBase, SearchScope scope, Int32 sizeLimit, Int32 timeLimit, LDAPFilter filter, String[] attributes, IList`1 controls, 
                 CancellationToken cancelToken, PSCmdlet cmdlet)+MoveNext()
                    at PSOpenAD.Commands.GetOpenADOperation`1.ProcessRecord() in /home/runner/work/PSOpenAD/PSOpenAD/src/Commands/OpenADObject.cs:line 189
                    at System.Management.Automation.Cmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()

```

**Comment by Denney-tech** [comment] 2022-06-10 20:46
I can reproduce this error with Get-OpenADUser over ldaps as well. Same CancellationToken error.

**Comment by jborean93** [comment] 2022-06-13 05:53
Thanks for the bug report. I need to enable some debug logging so we can see what the raw LDAP messages look like and why it's failing to decode the raw ASN.1 structures that are being received. I'm hoping to finish that off sometime this week and push out the next preview for you to try out so we can figure out what the problem is here.

If you are feeling up to it you can try and compile the code right now and step through the calls to [ReceiveData](https://github.com/jborean93/PSOpenAD/blob/03d1c1be7b030a992aa075c1e48489de67ace2e0/src/LDAP/LDAPSession.cs#L123) until it fails. Might be easier to just do a big `try/catch` around it and do `Console.WriteLine(Convert.ToBase64String(data));` to see what payload is failing to be parsed.

**Comment by Denney-tech** [comment] 2022-06-14 13:13
Can you add what you suggest as Debug output and push into the next preview build?  I.e. I could run `$computers = Get-OpenADComputer -Server ldaps://dc01.contoso.com:636 -Verbose -Debug` and the default $DebugPreference and $ConfirmPreference settings would make me step through the Debug: stream.

It might be nice to have actual Debug out for this module while it lives in preview, and perhaps even in actual release so long as there's no security concerns.

**Comment by Denney-tech** [comment] 2022-06-14 13:15
I did build the source yesterday and tested it, but the StackTrace wasn't much more detailed. Will rebuild again today since you pushed quite a few changes.

**Comment by Denney-tech** [comment] 2022-06-14 18:14
Here's the exception from the most recent build:

```
PS /mnt/c/Users/foo/Sources/PSOpenAD/output/PSOpenAD/0.1.0> $Error[0].Exception

DiagnosticsMessage :
ResultCode         : Other
TargetSite         : PSOpenAD.LDAP.LDAPMessage WaitForMessage(Int32, System.Nullable`1[System.Int32], System.Threading.CancellationToken)
Message            : Message recv failure: The encoded length exceeds the number of bytes remaining in the input buffer.
Data               : {}
InnerException     : System.Formats.Asn1.AsnContentException: The encoded length exceeds the number of bytes remaining in the input buffer.
                        at System.Formats.Asn1.AsnDecoder.ReadSequence(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& contentOffset, Int32& contentLength, Int32& bytesConsumed, Nullable`1 expectedTag)
                        at PSOpenAD.LDAP.LDAPSession.ReceiveData(ReadOnlySpan`1 data, Int32& bytesConsumed) in /mnt/c/Users/foo/Sources/PSOpenAD/src/LDAP/LDAPSession.cs:line 139
                        at PSOpenAD.OpenADConnection.TryReadMessage(ReadOnlySpan`1 data) in /mnt/c/Users/foo/Sources/PSOpenAD/src/Connection.cs:line 374
                        at PSOpenAD.OpenADConnection.RecvProcess(PipeReader reader) in /mnt/c/Users/foo/Sources/PSOpenAD/src/Connection.cs:line 312
HelpLink           :
Source             : PSOpenAD
HResult            : -2146233088
StackTrace         :    at PSOpenAD.OpenADConnection.WaitForMessage(Int32 messageId, Nullable`1 timeout, CancellationToken cancelToken) in /mnt/c/Users/foo/Sources/PSOpenAD/src/Connection.cs:line 67
                        at PSOpenAD.Operations.LdapSearchRequest(OpenADConnection connection, String searchBase, SearchScope scope, Int32 sizeLimit, Int32 timeLimit, LDAPFilter filter, String[] attributes, IList`1 controls,
                     CancellationToken cancelToken, PSCmdlet cmdlet)+MoveNext() in /mnt/c/Users/foo/Sources/PSOpenAD/src/Operations.cs:line 46
                        at PSOpenAD.Commands.GetOpenADOperation`1.ProcessRecord() in /mnt/c/Users/foo/Sources/PSOpenAD/src/Commands/OpenADObject.cs:line 194
                        at System.Management.Automation.Cmdlet.DoProcessRecord()
                        at System.Management.Automation.CommandProcessor.ProcessRecord()


PS /mnt/c/Users/foo/Sources/PSOpenAD/output/PSOpenAD/0.1.0> $Error[0].Exception.InnerException

TargetSite     : Void ReadSequence(System.ReadOnlySpan`1[System.Byte], System.Formats.Asn1.AsnEncodingRules, Int32 ByRef, Int32 ByRef, Int32 ByRef, System.Nullable`1[System.Formats.Asn1.Asn1Tag])
Message        : The encoded length exceeds the number of bytes remaining in the input buffer.
Data           : {}
InnerException :
HelpLink       :
Source         : System.Formats.Asn1
HResult        : -2146233088
StackTrace     :    at System.Formats.Asn1.AsnDecoder.ReadSequence(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& contentOffset, Int32& contentLength, Int32& bytesConsumed, Nullable`1 expectedTag)
                    at PSOpenAD.LDAP.LDAPSession.ReceiveData(ReadOnlySpan`1 data, Int32& bytesConsumed) in /mnt/c/Users/foo/Sources/PSOpenAD/src/LDAP/LDAPSession.cs:line 139
                    at PSOpenAD.OpenADConnection.TryReadMessage(ReadOnlySpan`1 data) in /mnt/c/Users/foo/Sources/PSOpenAD/src/Connection.cs:line 374
                    at PSOpenAD.OpenADConnection.RecvProcess(PipeReader reader) in /mnt/c/Users/foo/Sources/PSOpenAD/src/Connection.cs:line 312
```

**Comment by jborean93** [comment] 2022-06-14 19:01
> Can you add what you suggest as Debug output and push into the next preview build?

I would love to but the way the code is set up has the connection code run in a background thread and is not tied to cmdlet to write the messages to. I would need to set up a complex workflow to get this working at some point and even then it might miss things as it could receive messages in between cmdlet calls.

What I did add yesterday is the ability to do `-SessionOption (New-OpenADSessionOption -TracePath /tmp/PSOpenAD.log)` when you first create the session. For example

```powershell
$so = New-OpenADSessionOption -TracePath /tmp/PSOpenAD.log
$computers = Get-OpenADComputer -Server ldaps://dc01.contoso.com:636 -Verbose -SessionOption $so
```

Any LDAP messages sent and received by the client will be stored as a line with the data base64 encoded. You should find the last message it tried to process and failed is on the last line of the file.

I've also got a local change that I need to finalize that will raise a custom exception `UnpackLDAPMessageException` that contains a `byte[]` property of the data it tried to encode. That way `$Error[0].Exception.InnerException.LDAPMessage` will contain the data that it failed to unpack. I should have that ready within the next few hours for you to test if possible.

In saying all that, the stacktrace has been improved, it at least tells me where in the [ReceiveData method](https://github.com/jborean93/PSOpenAD/blob/80bcf00da074f630ff8110959868f4fdc9233ff0/src/LDAP/LDAPSession.cs#L139) it failed. What doesn't make sense is that the bytes being read passed the `HasEnoughData` check beforehand but it doesn't actually have enough data to unpack. Will have to see the raw data from the trace path or when I've added the custom exception to capture this to figure out why this is happening.

**Comment by jborean93** [comment] 2022-06-14 20:27
The `UnpackLDAPMessageException` has just been merged https://github.com/jborean93/PSOpenAD/pull/36.

**Comment by jborean93** [comment] 2022-06-14 21:47
PSOpenAD `0.1.0-preview4` was just released which includes these changes and will hopefully make it easier to debug these problems. It would be great if you could share the trace messages so I can see the whole exchange but I understand that it will contain data about your org and if you don't wish to share it publicly.

**Comment by Denney-tech** [comment] 2022-06-14 23:24
It does contain data about my org, so do not wish to share it at the moment. I don't see anything in particular standing out at the moment, but I have a few ideas on things to check.

**Closed** 2022-06-15 19:12 UTC

**Comment by jborean93** [comment] 2022-06-15 19:14
Thanks for working through this one and sharing the information you did. Appreciate the patience you've had with it.
